package il.cshaifasweng.OCSFMediatorExample.entities;

import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

@Entity
@DiscriminatorValue("ManagerWorker")
public class Manager extends Worker implements Serializable {

    // Requests made by the manager
    @OneToMany(mappedBy = "manager")
    private List<Request> requests = new ArrayList<>();

    // Reports generated by the manager
    @OneToMany(mappedBy = "manager", cascade = CascadeType.ALL)
    private List<Report> reports = new ArrayList<>();

    public Manager() {}

    public Manager(double salary, Branch branch, String name, String phoneNumber, String email, String password) {
        super(salary, branch, name, phoneNumber, email, password);
    }

    public List<Request> getRequests() {
        return requests;
    }

    public List<Report> getReports() {
        return reports;
    }

    public void setReports(List<Report> reports) {
        this.reports = reports;
    }

    public void addReport(Report report) {
        if (this.reports == null) {
            this.reports = new ArrayList<>();
        }
        this.reports.add(report);
        report.setManager(this);  // Set manager reference in Report
    }
}
